### ISSUE TITLE
Openstack upgrade should change rabbitmq channel before upgrading

### ISSUE THREAD

**Issue by Basdbruijne** [openstack-charmers/zaza-openstack-tests#1072]
In some of the openstack upgrades, we see:

```
INFO:root:About to upgrade the units of rabbitmq-server in serial (follower first: False)
INFO:root:Configuring leader / non leaders for rabbitmq-server
INFO:root:Pausing (leader) rabbitmq-server/1
INFO:root:Pausing (leader) rabbitmq-server/2
INFO:root:Finished Pausing (leader) rabbitmq-server/2
INFO:root:Finished Pausing (leader) rabbitmq-server/1
INFO:root:Finishing pausing application: rabbitmq-server
INFO:root:About to call '['juju', 'set-series', '-m', 'openstack', 'rabbitmq-server', 'jammy']'
WARNING:root:STDOUT: 
WARNING:root:STDERR: ERROR charm "rabbitmq-server" does not support jammy, force not used

Traceback (most recent call last):
  File "./solutions-qa-ci/bin/openstack_upgrade.py", line 121, in <module>
    main()
  File "./solutions-qa-ci/bin/openstack_upgrade.py", line 61, in main
    series_upgrader.test_200_run_series_upgrade()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/charm_tests/series_upgrade/parallel_tests.py", line 119, in test_200_run_series_upgrade
    upgrade_function(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/__init__.py", line 224, in _wrapper
    return future.result(timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/__init__.py", line 209, in _runner
    return await f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/utilities/parallel_series_upgrade.py", line 329, in async_serial_series_upgrade
    await series_upgrade_utils.async_set_series(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/utilities/series_upgrade.py", line 748, in async_set_series
    await os_utils.check_call(cmd)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/utilities/generic.py", line 389, in check_call
    raise subprocess.CalledProcessError(proc.returncode, cmd)
subprocess.CalledProcessError: Command '['juju', 'set-series', '-m', 'openstack', 'rabbitmq-server', 'jammy']' returned non-zero exit status 1.
Build timed out (after 180 minutes). Marking the build as aborted.
```

Rabbitmq is initially installed with 3.8/stable, but the automation should upgrade it to 3.9/stable before switching to jammy.

**Comment by ajkavanagh** [comment]
There's essentially a gap in the series-upgrade set of functions that doesn't take into account charmhub channels.  Thus it needs a whole overhaul to add charmhub channel awareness for series and openstack upgrades.
