### ISSUE TITLE
TypeError: series_upgrade_non_leaders_first() got an unexpected keyword argument 'pause_non_leader_primary'

### ISSUE THREAD

**Issue by AurelienLourot** [openstack-charmers/zaza-openstack-tests#228]
```
07:20:08 machine-32 series upgrade complete
07:20:08 
07:20:08 Upgrade series for machine "32" has successfully completed
07:20:08 2020-04-11 07:20:03 [INFO] Running run_post_upgrade_functions []
07:20:08 2020-04-11 07:20:03 [INFO] Waiting for workload status 'active' on nova-compute/1
07:20:08 2020-04-11 07:20:05 [INFO] Set series on nova-compute to xenial
07:20:08 2020-04-11 07:20:06 [WARNING] About to upgrade mongodb
07:20:08 Traceback (most recent call last):
07:20:08   File "/tmp/tmp.vXwvaGdcuA/mojo-openstack-specs/trusty/osci-mojo/spec/specs/full_stack/next_series_upgrade/mitaka/series_upgrade.py", line 42, in <module>
07:20:08     sys.exit(series_upgrade_test.test_200_run_series_upgrade())
07:20:08   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/openstack/charm_tests/series_upgrade/tests.py", line 94, in test_200_run_series_upgrade
07:20:08     files=self.files,
07:20:08 TypeError: series_upgrade_non_leaders_first() got an unexpected keyword argument 'pause_non_leader_primary'
```

http://osci:8080/view/MojoMatrix/job/mojo_runner/22110/console

Probably https://github.com/openstack-charmers/zaza-openstack-tests/commit/71b9d5a6fba1f06f5869726d4853f38c53b285e9#diff-572ab3d6fed94d02e79792f13f97053f

**Comment by andrewdmcleod** [comment]
This is probably related:

TypeError: series_upgrade_non_leaders_first() got an unexpected keyword argument 'pause_non_leader_subordinate'

**Comment by ajkavanagh** [comment]
Hit it again on trusty-mitaka (related to a mongo db upgrade):

```
2020-05-09 02:12:58 [INFO] Waiting for workload status 'active' on rabbitmq-server/2
2020-05-09 02:13:00 [INFO] Set series on rabbitmq-server to xenial
2020-05-09 02:13:00 [INFO] Running complete-cluster-series-upgrade action on leader
2020-05-09 02:13:10 [WARNING] About to upgrade mongodb
Traceback (most recent call last):
  File "/tmp/tmp.hrYD1L0KGP/mojo-openstack-specs/trusty/osci-mojo/spec/specs/full_stack/next_series_upgrade/mitaka/series_upgrade.py", line 42, in <module>
    sys.exit(series_upgrade_test.test_200_run_series_upgrade())
  File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/openstack/charm_tests/series_upgrade/tests.py", line 94, in test_200_run_series_upgrade
    files=self.files,
TypeError: series_upgrade_non_leaders_first() got an unexpected keyword argument 'pause_non_leader_subordinate'
```

http://10.245.162.58:8080/job/mojo_runner/22413/
