### ISSUE TITLE
[Series upgrade][trusty-mitaka] heat/0 failed due to sharedb relation changed WHILST mysql was still in paused state (test had continued)

### ISSUE THREAD

**Issue by ajkavanagh** [openstack-charmers/zaza-openstack-tests#254]
Essentially, it looks like the test had continued (machine 22 upgraded - which has mysql) but then the heat/0 unit failed when trying to connect to the mysql database:

```
05:42:19 2020-05-02 05:39:01 [INFO] Reboot mysql/1
05:42:19 Failed to start reboot.target: Connection timed out
05:42:19 See system logs and 'systemctl status reboot.target' for details.
05:42:19 2020-05-02 05:39:26 [INFO] Waiting for workload status 'blocked' on mysql/1
05:42:19 2020-05-02 05:39:52 [INFO] Waiting for model idleness
05:42:19 2020-05-02 05:39:53 [INFO] Set origin on mysql
05:42:19 2020-05-02 05:39:53 [INFO] Set origin on mysql to source
05:42:19 2020-05-02 05:39:55 [INFO] Complete series upgrade on 22
05:42:19 machine-22 complete phase started
05:42:19 machine-22 started unit agents after series upgrade
05:42:19 mysql/1 post-series-upgrade hook running
05:42:19 mysql/1 post-series-upgrade completed
05:42:19 mysql-hacluster/0 post-series-upgrade hook running
05:42:19 mysql-hacluster/0 post-series-upgrade completed
05:42:19 
05:42:19 Upgrade series for machine "22" has successfully completed
05:42:19 Traceback (most recent call last):
05:42:19   File "/tmp/tmp.eZaH0SXLjw/mojo-openstack-specs/trusty/osci-mojo/spec/specs/full_stack/next_series_upgrade/mitaka/series_upgrade.py", line 42, in <module>
05:42:19     sys.exit(series_upgrade_test.test_200_run_series_upgrade())
05:42:19   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/openstack/charm_tests/series_upgrade/tests.py", line 94, in test_200_run_series_upgrade
05:42:19     files=self.files,
05:42:19   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/openstack/utilities/series_upgrade.py", line 322, in series_upgrade_application
05:42:19     post_upgrade_functions=post_upgrade_functions)
05:42:19   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/openstack/utilities/series_upgrade.py", line 578, in series_upgrade
05:42:19     model.block_until_all_units_idle()
05:42:19   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/__init__.py", line 48, in _wrapper
05:42:19     return run(_run_it())
05:42:19   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/__init__.py", line 36, in run
05:42:19     return task.result()
05:42:19   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
05:42:19     raise self._exception
05:42:19   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
05:42:19     result = coro.send(None)
05:42:19   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/__init__.py", line 47, in _run_it
05:42:19     return await f(*args, **kwargs)
05:42:19   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/model.py", line 1040, in async_block_until_all_units_idle
05:42:19     raise UnitError(errored_units)
05:42:19 zaza.model.UnitError: Units heat/0 in error state
```

Smoking gun may be:

```
05:42:19 2020-05-02 05:39:01 [INFO] Reboot mysql/1
05:42:19 Failed to start reboot.target: Connection timed out
```

heat/0 failed with

```
2020-05-02 05:42:14 DEBUG shared-db-relation-changed ERROR: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '172.17.107.231' ([Errno 113] No route to host)")
```

mysql/1 relevant info:

```
mysql/0                    maintenance  idle       21       172.17.107.20   3306/tcp                                 Paused. Use 'resume' action to resume normal service.
  mysql-hacluster/1        maintenance  idle                172.17.107.20                                            Paused. Use 'resume' action to resume normal service.
mysql/1*                   active       executing  22       172.17.107.45   3306/tcp                                 (config-changed) Unit is ready
  mysql-hacluster/0*       blocked      executing           172.17.107.45                                            (post-series-upgrade) Resource: res_mysql_monitor not running
mysql/2                    maintenance  idle       23       172.17.107.64   3306/tcp                                 Paused. Use 'resume' action to resume normal service.
  mysql-hacluster/2        maintenance  idle                172.17.107.64                                            Paused. Use 'resume' action to resume normal service.
```

Strategy:

Trace whether there is a race/error in determining whether the mysql post-series upgrade (or series upgrade in general) verification of complete is actually not correct and is assuming it is complete when it is not.

**Comment by gnuoy** [comment]
Can you see which version of mysql charm is being used ? The trusty version
lacks maintenance mode awareness and it likely to lead to this error. I
have a wip which I'd like to land but atm I'm not sure how to propose
stuff to cs:~openstackcharms/trusty/percona-cluster

**Comment by ajkavanagh** [comment]
From the juju status, it looks like:

2020-05-02 00:03:20 [INFO] Downloading cs:percona-cluster-276 from charm store to percona-cluster
