### ISSUE TITLE
Keystone SAML Mellon tests are failing

### ISSUE THREAD

**Issue by thedac** [openstack-charmers/zaza-openstack-tests#293]
The test originally was doing a simple check that we were redirected. It is time to write a test fixture so that we can control the IDP side of the equation. Regardless the tests as they exist need updating.

Relying on https://samltest.id is probably not a good idea. It has given 503 errors.

Also, the certificate generation code in Zaza is not removing the ---- END CERTIFICATE ---- string before attaching it as a resource to keystone-saml-mellon.

Related is focal OpenStack dashboard returning 500 errors: https://bugs.launchpad.net/charm-keystone-saml-mellon/+bug/1879791

**Comment by thedac** [comment]
https://review.opendev.org/#/c/731730/ Maybe the resolution to these problems.

**Comment by thedac** [comment]
The problem still exists on the focal-ussuri bundle:

2020-08-06 22:06:24 [INFO] ERROR
2020-08-06 22:06:24 [INFO] ======================================================================
2020-08-06 22:06:24 [INFO] ERROR: test_saml_mellon_redirects (zaza.openstack.charm_tests.saml_mellon.tests.CharmKeystoneSAMLMellonTest)
2020-08-06 22:06:24 [INFO] Validate the horizon -> keystone -> IDP redirects.
2020-08-06 22:06:24 [INFO] ----------------------------------------------------------------------
2020-08-06 22:06:24 [INFO] Traceback (most recent call last):
2020-08-06 22:06:24 [INFO]   File "/home/ubuntu/dev/keystone-saml-mellon/build/builds/keystone-saml-mellon/.tox/func/lib/python3.6/site-packages/zaza/openstack/charm_tests/saml_mellon/tests.py",
 line 149, in test_saml_mellon_redirects
2020-08-06 22:06:24 [INFO]     _do_redirect_check(url, region, idp_expect, horizon_expect)
2020-08-06 22:06:24 [INFO]   File "/home/ubuntu/dev/keystone-saml-mellon/build/builds/keystone-saml-mellon/.tox/func/lib/python3.6/site-packages/zaza/openstack/charm_tests/saml_mellon/tests.py",
 line 145, in _do_redirect_check
2020-08-06 22:06:24 [INFO]     raise FailedToReachIDP(msg)
2020-08-06 22:06:24 [INFO] zaza.openstack.charm_tests.saml_mellon.tests.FailedToReachIDP: FAILURE code=<Response [500]> text=


In the Apache error log:

[Thu Aug 06 22:21:06.824923 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944] Internal Server Error: /horizon/auth/login/
[Thu Aug 06 22:21:06.824929 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944] Traceback (most recent call last):
[Thu Aug 06 22:21:06.824935 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]   File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 34, in inner
[Thu Aug 06 22:21:06.824940 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]     response = get_response(request)
[Thu Aug 06 22:21:06.824946 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]   File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 115, in _get_response
[Thu Aug 06 22:21:06.824964 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]     response = self.process_exception_by_middleware(e, request)
[Thu Aug 06 22:21:06.824969 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]   File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 113, in _get_response
[Thu Aug 06 22:21:06.824974 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Aug 06 22:21:06.824979 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]   File "/usr/lib/python3/dist-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
[Thu Aug 06 22:21:06.824983 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]     return view(request, *args, **kwargs)
[Thu Aug 06 22:21:06.824988 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]   File "/usr/lib/python3/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
[Thu Aug 06 22:21:06.824993 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]     response = view_func(request, *args, **kwargs)
[Thu Aug 06 22:21:06.824997 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]   File "/usr/lib/python3/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
[Thu Aug 06 22:21:06.825002 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]     response = view_func(request, *args, **kwargs)
[Thu Aug 06 22:21:06.825006 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]   File "/usr/lib/python3/dist-packages/openstack_auth/views.py", line 77, in login
[Thu Aug 06 22:21:06.825011 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]     auth_url = forms.get_region_endpoint(region_id)
[Thu Aug 06 22:21:06.825015 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]   File "/usr/lib/python3/dist-packages/openstack_auth/forms.py", line 36, in get_region_endpoint
[Thu Aug 06 22:21:06.825020 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944]     return all_regions[int(region_id)][0]
[Thu Aug 06 22:21:06.825024 2020] [wsgi:error] [pid 62607:tid 140682558416640] [remote 10.5.0.6:36944] ValueError: invalid literal for int() with base 10: 'https://10.5.58.6:5000/v3'

The problem appears to be the "region" setting which is set to the keystone VIP for bionic but on focal it is breaking.

NOTE: This is purely a testing failure the charm is functional.

**Comment by thedac** [comment]
Closed with https://github.com/openstack-charmers/zaza-openstack-tests/pull/378
