### ISSUE TITLE
KeyError: getting subordinate charm after pause/resume - change in libjuju / zaza

### ISSUE THREAD

**Issue by ajkavanagh** [openstack-charmers/zaza-openstack-tests#307]
[charm-trilio-data-mover] KeyError: 'trilio-data-mover/0' during "ERROR: test_pause_resume (zaza.openstack.charm_tests.trilio.tests.TrilioDataMoverTest)"

It looks like something may have changed in libjuju / zaza around being able to get subordinates by key ... it obviously used to work, so something strange is going on:

https://openstack-ci-reports.ubuntu.com/artifacts/test_charm_pipeline_func_smoke/openstack/charm-trilio-data-mover/732679/1/16935/test_charm_func_smoke_17759/func.txt

https://review.opendev.org/#/c/732679/

```
2020-06-02 20:05:42 [INFO] ERROR: test_pause_resume (zaza.openstack.charm_tests.trilio.tests.TrilioDataMoverTest)
2020-06-02 20:05:42 [INFO] Run pause and resume tests.
2020-06-02 20:05:42 [INFO] ----------------------------------------------------------------------
2020-06-02 20:05:42 [INFO] Traceback (most recent call last):
2020-06-02 20:05:42 [INFO]   File "/tmp/tmp.2ABKxbTwEc/func-smoke/lib/python3.5/site-packages/zaza/openstack/charm_tests/trilio/tests.py", line 295, in test_pause_resume
2020-06-02 20:05:42 [INFO]     with self.pause_resume(self.services, pgrep_full=False):
2020-06-02 20:05:42 [INFO]   File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
2020-06-02 20:05:42 [INFO]     return next(self.gen)
2020-06-02 20:05:42 [INFO]   File "/tmp/tmp.2ABKxbTwEc/func-smoke/lib/python3.5/site-packages/zaza/openstack/charm_tests/test_utils.py", line 352, in pause_resume
2020-06-02 20:05:42 [INFO]     model_name=self.model_name)
2020-06-02 20:05:42 [INFO]   File "/tmp/tmp.2ABKxbTwEc/func-smoke/lib/python3.5/site-packages/zaza/__init__.py", line 48, in _wrapper
2020-06-02 20:05:42 [INFO]     return run(_run_it())
2020-06-02 20:05:42 [INFO]   File "/tmp/tmp.2ABKxbTwEc/func-smoke/lib/python3.5/site-packages/zaza/__init__.py", line 36, in run
2020-06-02 20:05:42 [INFO]     return task.result()
2020-06-02 20:05:42 [INFO]   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
2020-06-02 20:05:42 [INFO]     raise self._exception
2020-06-02 20:05:42 [INFO]   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
2020-06-02 20:05:42 [INFO]     result = coro.send(None)
2020-06-02 20:05:42 [INFO]   File "/tmp/tmp.2ABKxbTwEc/func-smoke/lib/python3.5/site-packages/zaza/__init__.py", line 47, in _run_it
2020-06-02 20:05:42 [INFO]     return await f(*args, **kwargs)
2020-06-02 20:05:42 [INFO]   File "/tmp/tmp.2ABKxbTwEc/func-smoke/lib/python3.5/site-packages/zaza/model.py", line 1480, in async_block_until_unit_wl_status
2020-06-02 20:05:42 [INFO]     await async_block_until(_unit_status, timeout=timeout)
2020-06-02 20:05:42 [INFO]   File "/tmp/tmp.2ABKxbTwEc/func-smoke/lib/python3.5/site-packages/zaza/model.py", line 1162, in async_block_until
2020-06-02 20:05:42 [INFO]     await asyncio.wait_for(_block(), timeout, loop=loop)
2020-06-02 20:05:42 [INFO]   File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
2020-06-02 20:05:42 [INFO]     return fut.result()
2020-06-02 20:05:42 [INFO]   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
2020-06-02 20:05:42 [INFO]     raise self._exception
2020-06-02 20:05:42 [INFO]   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
2020-06-02 20:05:42 [INFO]     result = coro.send(None)
2020-06-02 20:05:42 [INFO]   File "/tmp/tmp.2ABKxbTwEc/func-smoke/lib/python3.5/site-packages/zaza/model.py", line 1156, in _block
2020-06-02 20:05:42 [INFO]     result = await c()
2020-06-02 20:05:42 [INFO]   File "/tmp/tmp.2ABKxbTwEc/func-smoke/lib/python3.5/site-packages/zaza/model.py", line 1453, in _unit_status
2020-06-02 20:05:42 [INFO]     v = model_status.applications[app]['units'][unit_name][
2020-06-02 20:05:42 [INFO] KeyError: 'trilio-data-mover/0'
```

**Comment by ajkavanagh** [comment]
Also affecting [charm-ovn-chassis]:

```
2020-06-02 18:50:15 [INFO] ERROR: test_pause_resume (zaza.openstack.charm_tests.ovn.tests.ChassisCharmOperationTest)
2020-06-02 18:50:15 [INFO] Run pause and resume tests.
2020-06-02 18:50:15 [INFO] ----------------------------------------------------------------------
2020-06-02 18:50:15 [INFO] Traceback (most recent call last):
2020-06-02 18:50:15 [INFO]   File "/tmp/tmp.eDUJ5G4M93/func-smoke/lib/python3.5/site-packages/zaza/openstack/charm_tests/ovn/tests.py", line 44, in test_pause_resume
2020-06-02 18:50:15 [INFO]     with self.pause_resume(self.services):
2020-06-02 18:50:15 [INFO]   File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
2020-06-02 18:50:15 [INFO]     return next(self.gen)
2020-06-02 18:50:15 [INFO]   File "/tmp/tmp.eDUJ5G4M93/func-smoke/lib/python3.5/site-packages/zaza/openstack/charm_tests/test_utils.py", line 390, in pause_resume
2020-06-02 18:50:15 [INFO]     model_name=self.model_name)
2020-06-02 18:50:15 [INFO]   File "/tmp/tmp.eDUJ5G4M93/func-smoke/lib/python3.5/site-packages/zaza/__init__.py", line 48, in _wrapper
2020-06-02 18:50:15 [INFO]     return run(_run_it())
2020-06-02 18:50:15 [INFO]   File "/tmp/tmp.eDUJ5G4M93/func-smoke/lib/python3.5/site-packages/zaza/__init__.py", line 36, in run
2020-06-02 18:50:15 [INFO]     return task.result()
2020-06-02 18:50:15 [INFO]   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
2020-06-02 18:50:15 [INFO]     raise self._exception
2020-06-02 18:50:15 [INFO]   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
2020-06-02 18:50:15 [INFO]     result = coro.send(None)
2020-06-02 18:50:15 [INFO]   File "/tmp/tmp.eDUJ5G4M93/func-smoke/lib/python3.5/site-packages/zaza/__init__.py", line 47, in _run_it
2020-06-02 18:50:15 [INFO]     return await f(*args, **kwargs)
2020-06-02 18:50:15 [INFO]   File "/tmp/tmp.eDUJ5G4M93/func-smoke/lib/python3.5/site-packages/zaza/model.py", line 1480, in async_block_until_unit_wl_status
2020-06-02 18:50:15 [INFO]     await async_block_until(_unit_status, timeout=timeout)
2020-06-02 18:50:15 [INFO]   File "/tmp/tmp.eDUJ5G4M93/func-smoke/lib/python3.5/site-packages/zaza/model.py", line 1162, in async_block_until
2020-06-02 18:50:15 [INFO]     await asyncio.wait_for(_block(), timeout, loop=loop)
2020-06-02 18:50:15 [INFO]   File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
2020-06-02 18:50:15 [INFO]     return fut.result()
2020-06-02 18:50:15 [INFO]   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
2020-06-02 18:50:15 [INFO]     raise self._exception
2020-06-02 18:50:15 [INFO]   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
2020-06-02 18:50:15 [INFO]     result = coro.send(None)
2020-06-02 18:50:15 [INFO]   File "/tmp/tmp.eDUJ5G4M93/func-smoke/lib/python3.5/site-packages/zaza/model.py", line 1156, in _block
2020-06-02 18:50:15 [INFO]     result = await c()
2020-06-02 18:50:15 [INFO]   File "/tmp/tmp.eDUJ5G4M93/func-smoke/lib/python3.5/site-packages/zaza/model.py", line 1453, in _unit_status
2020-06-02 18:50:15 [INFO]     v = model_status.applications[app]['units'][unit_name][
2020-06-02 18:50:15 [INFO] KeyError: 'ovn-chassis/0'
```

**Comment by gnuoy** [comment]
I believe this was fixed by https://github.com/openstack-charmers/zaza/commit/45099068937dcecf48e992fbdc3f8766bfbde944

**Comment by ajkavanagh** [comment]
Yes, confirmed fixed.  Thanks very much @gnuoy
