### ISSUE TITLE
Hacluster test has unbound variable

### ISSUE THREAD

**Issue by thedac** [openstack-charmers/zaza-openstack-tests#327]
See Test artifacts https://openstack-ci-reports.ubuntu.com/artifacts/test_charm_pipeline_func_smoke/openstack/charm-hacluster/734150/1/17094/consoleText.test_charm_func_smoke_17890.txt

2020-06-08 17:19:50 [INFO] ======================================================================
2020-06-08 17:19:50 [INFO] ERROR: test_900_action_cleanup (zaza.openstack.charm_tests.hacluster.tests.HaclusterTest)
2020-06-08 17:19:50 [INFO] The services can be cleaned up.
2020-06-08 17:19:50 [INFO] ----------------------------------------------------------------------
2020-06-08 17:19:50 [INFO] Traceback (most recent call last):
2020-06-08 17:19:50 [INFO]   File "/tmp/tmp.msnztYxDUy/func-smoke/lib/python3.5/site-packages/zaza/openstack/charm_tests/hacluster/tests.py", line 50, in test_900_action_cleanup
2020-06-08 17:19:50 [INFO]     if primary_status["units"][leader].get("subordinates"):
2020-06-08 17:19:50 [INFO] UnboundLocalError: local variable 'primary_status' referenced before assignment
2020-06-08 17:19:50 [INFO] ======================================================================
2020-06-08 17:19:50 [INFO] ERROR: test_910_pause_and_resume (zaza.openstack.charm_tests.hacluster.tests.HaclusterTest)
2020-06-08 17:19:50 [INFO] The services can be paused and resumed.
2020-06-08 17:19:50 [INFO] ----------------------------------------------------------------------
2020-06-08 17:19:50 [INFO] Traceback (most recent call last):
2020-06-08 17:19:50 [INFO]   File "/tmp/tmp.msnztYxDUy/func-smoke/lib/python3.5/site-packages/zaza/openstack/charm_tests/hacluster/tests.py", line 89, in test_910_pause_and_resume
2020-06-08 17:19:50 [INFO]     if primary_status["units"][leader].get("subordinates"):
2020-06-08 17:19:50 [INFO] UnboundLocalError: local variable 'primary_status' referenced before assignment
2020-06-08 17:19:50 [INFO] ----------------------------------------------------------------------

**Comment by gnuoy** [comment]
This was fixed in https://github.com/openstack-charmers/zaza-openstack-tests/commit/d76105e4db3580c3ddf5ac9ff0f778f0ea895fcb
