### ISSUE TITLE
PerconaClusterColdStartTest fails because of a race condition.

### ISSUE THREAD

**Issue by camille-rodriguez** [openstack-charmers/zaza-openstack-tests#44]
Used in the cham-percona-cluster, the test PerconaClusterColdStartTest, specifically test_100_cold_start_bootstrap, tries to start instances before these are completely shutoff. This causes the test to fail. 

2019-08-30 17:42:43 [INFO] ## Running Test zaza.openstack.charm_tests.mysql.tests.PerconaClusterColdStartTest ##
2019-08-30 17:42:44 [INFO] Using keystone API V3 (or later) for overcloud auth
2019-08-30 17:42:45 [INFO] AUTH_URL: http://10.245.161.156:5000/v3, api_ver: 3
2019-08-30 17:42:45 [INFO] Using keystone API V3 (or later) for undercloud auth
2019-08-30 17:42:45 [INFO] test_100_cold_start_bootstrap (zaza.openstack.charm_tests.mysql.tests.PerconaClusterColdStartTest)
2019-08-30 17:42:45 [INFO] Bootstrap a non-leader node.
2019-08-30 17:42:45 [INFO]  ... 
2019-08-30 17:42:46 [INFO] Stopping instances: ['15795301-d477-48e8-897c-011a6c43a28e', '327f5ad2-a8d0-4c94-a1d6-db704140e7d1', '921dd945-fd52-417c-abc7-3868a33701a4']
sleep 60 sec
sleep done
2019-08-30 17:43:47 [INFO] Starting instances: ['921dd945-fd52-417c-abc7-3868a33701a4', '327f5ad2-a8d0-4c94-a1d6-db704140e7d1', '15795301-d477-48e8-897c-011a6c43a28e']
2019-08-30 17:43:47 [INFO] ERROR
2019-08-30 17:43:47 [INFO] ======================================================================
2019-08-30 17:43:47 [INFO] ERROR: test_100_cold_start_bootstrap (zaza.openstack.charm_tests.mysql.tests.PerconaClusterColdStartTest)
2019-08-30 17:43:47 [INFO] Bootstrap a non-leader node.
2019-08-30 17:43:47 [INFO] ----------------------------------------------------------------------
2019-08-30 17:43:47 [INFO] Traceback (most recent call last):
2019-08-30 17:43:47 [INFO]   File "/home/ubuntu/charms/percona-cluster/.tox/func/lib/python3.6/site-packages/zaza/openstack/charm_tests/mysql/tests.py", line 294, in test_100_cold_start_bootstrap
2019-08-30 17:43:47 [INFO]     self.nova_client.servers.start(uuid)
2019-08-30 17:43:47 [INFO]   File "/home/ubuntu/charms/percona-cluster/.tox/func/lib/python3.6/site-packages/novaclient/v2/servers.py", line 1107, in start
2019-08-30 17:43:47 [INFO]     return self._action('os-start', server, None)
2019-08-30 17:43:47 [INFO]   File "/home/ubuntu/charms/percona-cluster/.tox/func/lib/python3.6/site-packages/novaclient/v2/servers.py", line 2073, in _action
2019-08-30 17:43:47 [INFO]     info=info, **kwargs)
2019-08-30 17:43:47 [INFO]   File "/home/ubuntu/charms/percona-cluster/.tox/func/lib/python3.6/site-packages/novaclient/v2/servers.py", line 2084, in _action_return_resp_and_body
2019-08-30 17:43:47 [INFO]     return self.api.client.post(url, body=body)
2019-08-30 17:43:47 [INFO]   File "/home/ubuntu/charms/percona-cluster/.tox/func/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 392, in post
2019-08-30 17:43:47 [INFO]     return self.request(url, 'POST', **kwargs)
2019-08-30 17:43:47 [INFO]   File "/home/ubuntu/charms/percona-cluster/.tox/func/lib/python3.6/site-packages/novaclient/client.py", line 78, in request
2019-08-30 17:43:47 [INFO]     raise exceptions.from_response(resp, body, url, method)
2019-08-30 17:43:47 [INFO] novaclient.exceptions.Conflict: Cannot 'start' instance 921dd945-fd52-417c-abc7-3868a33701a4 while it is in vm_state active (HTTP 409) (Request-ID: req-aa857f23-163e-4c1e-b4a5-c32f32145b5c)
2019-08-30 17:43:47 [INFO] ----------------------------------------------------------------------
2019-08-30 17:43:47 [INFO] Ran 1 test in 64.434s
2019-08-30 17:43:47 [INFO] FAILED
2019-08-30 17:43:47 [INFO]  (errors=1)
Traceback (most recent call last):
  File "/home/ubuntu/charms/percona-cluster/.tox/func/bin/functest-run-suite", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/charms/percona-cluster/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 140, in main
    bundle=args.bundle)
  File "/home/ubuntu/charms/percona-cluster/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 76, in func_test_runner
    test_steps.get(model_alias, []))
  File "/home/ubuntu/charms/percona-cluster/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/test.py", line 68, in test
    run_test_list(tests)
  File "/home/ubuntu/charms/percona-cluster/.tox/func/lib/python3.6/site-packages/zaza/charm_lifecycle/test.py", line 62, in run_test_list
    assert test_result.wasSuccessful(), "Test run failed"
AssertionError: Test run failed

**Comment by camille-rodriguez** [comment]
Fixed with https://github.com/openstack-charmers/zaza-openstack-tests/pull/45
