### ISSUE TITLE
FullCloudCharmUpgradeTest is broken: class uses LTSGuestCreateTest without running setupClass()

### ISSUE THREAD

**Issue by ajkavanagh** [openstack-charmers/zaza-openstack-tests#451]
Essentially:

 * `LTSGuestCreateTest()` is 'designed' to be used as a UnitTest class, in that it is configured via a `setupClass` method rather than the `__init__()` method.
 * `FullCloudCharmUpgradeTest` uses `LTSGuestCreateTest` as an 'ordinary' class which means that it doesn't call `setupClass`.

This results in the following traceback:

```
2020-10-19 13:42:01 [INFO] ERROR: test_200_run_charm_upgrade (zaza.openstack.charm_tests.charm_upgrade.tests.FullCloudCharmUpgradeTest)
2020-10-19 13:42:01 [INFO] Run charm upgrade.
2020-10-19 13:42:01 [INFO] ----------------------------------------------------------------------
2020-10-19 13:42:01 [INFO] Traceback (most recent call last):
2020-10-19 13:42:01 [INFO]   File "/home/ubuntu/git/github.com/openstack-charmers/charmed-openstack-tester/.tox/series-upgrade/lib/python3.6/site-packages/zaza/openstack/charm_tests/test_utils.py", line 577, in launch_guest
2020-10-19 13:42:01 [INFO]     instance_name)
2020-10-19 13:42:01 [INFO]   File "/home/ubuntu/git/github.com/openstack-charmers/charmed-openstack-tester/.tox/series-upgrade/lib/python3.6/site-packages/zaza/openstack/charm_tests/test_utils.py", line 622, in retrieve_guest
2020-10-19 13:42:01 [INFO]     return self.nova_client.servers.find(name=guest_name)
2020-10-19 13:42:01 [INFO] AttributeError: 'LTSGuestCreateTest' object has no attribute 'nova_client'
```

The base class of `LTSGuestCreateTest` probably needs to be split into the UnitTest version which then uses an ordinary version to do the work.

**Comment by ajkavanagh** [comment]
Fixed by #466
