### ISSUE TITLE
NeutronNetworkingTest ssh key failure

### ISSUE THREAD

**Issue by camille-rodriguez** [openstack-charmers/zaza-openstack-tests#48]
The test zaza.openstack.charm_tests.neutron.tests.NeutronNetworkingTest fails because of an issue with the public key format detected by paramiko in the test. This causes charms to fail the OSCI pipeline tests. 
(ref: https://openstack-ci-reports.ubuntu.com/artifacts/test_charm_pipeline_func_full/openstack/charm-neutron-api/678911/1/3746/consoleText.test_charm_func_full_7008.txt)

2019-08-29 21:09:55 [INFO] ======================================================================
2019-08-29 21:09:55 [INFO] ERROR: test_instances_have_networking (zaza.openstack.charm_tests.neutron.tests.NeutronNetworkingTest)
2019-08-29 21:09:55 [INFO] Validate North/South and East/West networking.
2019-08-29 21:09:55 [INFO] ----------------------------------------------------------------------
2019-08-29 21:09:55 [INFO] Traceback (most recent call last):
2019-08-29 21:09:55 [INFO]   File "/tmp/tmp.nTxMwgcNDI/func/lib/python3.5/site-packages/zaza/openstack/charm_tests/neutron/tests.py", line 150, in test_instances_have_networking
2019-08-29 21:09:55 [INFO]     vm_name='{}-ins-1'.format(self.RESOURCE_PREFIX))
2019-08-29 21:09:55 [INFO]   File "/tmp/tmp.nTxMwgcNDI/func/lib/python3.5/site-packages/zaza/openstack/configure/guest.py", line 142, in launch_instance
2019-08-29 21:09:55 [INFO]     privkey=openstack_utils.get_private_key(nova_utils.KEYPAIR_NAME))
2019-08-29 21:09:55 [INFO]   File "/tmp/tmp.nTxMwgcNDI/func/lib/python3.5/site-packages/zaza/openstack/utilities/openstack.py", line 2048, in ssh_test
2019-08-29 21:09:55 [INFO]     password=password, privkey=privkey, verify=verify)
2019-08-29 21:09:55 [INFO]   File "/tmp/tmp.nTxMwgcNDI/func/lib/python3.5/site-packages/zaza/openstack/utilities/openstack.py", line 2085, in ssh_command
2019-08-29 21:09:55 [INFO]     ssh.connect(ip, username=username, password='', pkey=key)
2019-08-29 21:09:55 [INFO]   File "/tmp/tmp.nTxMwgcNDI/func/lib/python3.5/site-packages/paramiko/client.py", line 446, in connect
2019-08-29 21:09:55 [INFO]     passphrase,
2019-08-29 21:09:55 [INFO]   File "/tmp/tmp.nTxMwgcNDI/func/lib/python3.5/site-packages/paramiko/client.py", line 764, in _auth
2019-08-29 21:09:55 [INFO]     raise saved_exception
2019-08-29 21:09:55 [INFO]   File "/tmp/tmp.nTxMwgcNDI/func/lib/python3.5/site-packages/paramiko/client.py", line 751, in _auth
2019-08-29 21:09:55 [INFO]     self._transport.auth_password(username, password)
2019-08-29 21:09:55 [INFO]   File "/tmp/tmp.nTxMwgcNDI/func/lib/python3.5/site-packages/paramiko/transport.py", line 1509, in auth_password
2019-08-29 21:09:55 [INFO]     return self.auth_handler.wait_for_response(my_event)
2019-08-29 21:09:55 [INFO]   File "/tmp/tmp.nTxMwgcNDI/func/lib/python3.5/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
2019-08-29 21:09:55 [INFO]     raise e
2019-08-29 21:09:55 [INFO] paramiko.ssh_exception.BadAuthenticationType: Bad authentication type; allowed types: ['publickey']
2019-08-29 21:09:55 [INFO] ----------------------------------------------------------------------
2019-08-29 21:09:55 [INFO] Ran 1 test in 196.225s
2019-08-29 21:09:55 [INFO] FAILED
2019-08-29 21:09:55 [INFO]  (errors=1)
Traceback (most recent call last):
  File "/tmp/tmp.nTxMwgcNDI/func/bin/functest-run-suite", line 10, in <module>
    sys.exit(main())
  File "/tmp/tmp.nTxMwgcNDI/func/lib/python3.5/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 140, in main
    bundle=args.bundle)
  File "/tmp/tmp.nTxMwgcNDI/func/lib/python3.5/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 76, in func_test_runner
    test_steps.get(model_alias, []))
  File "/tmp/tmp.nTxMwgcNDI/func/lib/python3.5/site-packages/zaza/charm_lifecycle/test.py", line 68, in test
    run_test_list(tests)
  File "/tmp/tmp.nTxMwgcNDI/func/lib/python3.5/site-packages/zaza/charm_lifecycle/test.py", line 62, in run_test_list
    assert test_result.wasSuccessful(), "Test run failed"
AssertionError: Test run failed
ERROR: InvocationError: '/tmp/tmp.nTxMwgcNDI/func/bin/functest-run-suite --keep-model'
___________________________________ summary ____________________________________
ERROR:   func: commands failed

**Comment by ryan-beisner** [comment]
@camille-rodriguez  Please raise this against the charm in launchpad, and add a bug task to charm-test-infra.

https://bugs.launchpad.net/charm-test-infra

**Comment by camille-rodriguez** [comment]
Okay, issue opened here https://bugs.launchpad.net/charm-test-infra/+bug/1843432
