### ISSUE TITLE
Neutron Gateway deferred restart test failing

### ISSUE THREAD

**Issue by gnuoy** [openstack-charmers/zaza-openstack-tests#553]
The deferred restart test is trying to run the deferred hooks action which is causing the test to fail:

```
2021-04-12 09:02:17 [INFO] Running restart action to clear deferred restarts                                                                                                                        [68/98190]
2021-04-12 09:02:17 [INFO] Running restart-services on neutron-gateway/0                                                                                                                                      
2021-04-12 09:03:58 [INFO] Triggering deferred restart via package change                                                                                                                                     
2021-04-12 09:04:04 [INFO] Checking openvswitch-switch is marked as needing restart in workload message of neutron-gateway/0                                                                                  
2021-04-12 09:04:04 [INFO] Checking openvswitch-switch is marked as needing restart in show-deferred-events action                                                                                            
2021-04-12 09:04:19 [INFO] openvswitch-switch in 1618218241 openvswitch-switch                       Package update and Package update in 1618218241 openvswitch-switch                       Package update
2021-04-12 09:04:19 [INFO] Running restart action to clear deferred restarts
2021-04-12 09:04:20 [INFO] Running restart-services on neutron-gateway/0                                                                                                                                      
2021-04-12 09:04:43 [INFO] Turning on auto restarts                                                                                                                                                           
2021-04-12 09:05:25 [INFO] Running run-deferred-hooks on neutron-gateway/0
2021-04-12 09:06:39 [INFO] ERROR                                                                                                                                                                              
2021-04-12 09:06:39 [INFO] ======================================================================                                                                                                             
2021-04-12 09:06:39 [INFO] ERROR: test_deferred_restarts (zaza.openstack.charm_tests.neutron.tests.NeutronGatewayDeferredRestartTest)
2021-04-12 09:06:39 [INFO] Run deferred restart tests.                                                                                                                                                        
2021-04-12 09:06:39 [INFO] ----------------------------------------------------------------------                                                                                                             
2021-04-12 09:06:39 [INFO] Traceback (most recent call last):  
2021-04-12 09:06:39 [INFO]   File "/home/ubuntu/work/branches/neutron-gateway/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/test_utils.py", line 1101, in test_deferred_restarts    
2021-04-12 09:06:39 [INFO]     self.check_clear_hooks()                                                                                                                                                       
2021-04-12 09:06:39 [INFO]   File "/home/ubuntu/work/branches/neutron-gateway/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/test_utils.py", line 793, in check_clear_hooks
2021-04-12 09:06:39 [INFO]     self.clear_hooks()                                                                                                                                                             
2021-04-12 09:06:39 [INFO]   File "/home/ubuntu/work/branches/neutron-gateway/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/test_utils.py", line 782, in clear_hooks
2021-04-12 09:06:39 [INFO]     model.run_action(
2021-04-12 09:06:39 [INFO]   File "/home/ubuntu/work/branches/neutron-gateway/.tox/func-target/lib/python3.8/site-packages/zaza/__init__.py", line 48, in _wrapper
2021-04-12 09:06:39 [INFO]     return run(_run_it())
2021-04-12 09:06:39 [INFO]   File "/home/ubuntu/work/branches/neutron-gateway/.tox/func-target/lib/python3.8/site-packages/zaza/__init__.py", line 36, in run
2021-04-12 09:06:39 [INFO]     return task.result() 
2021-04-12 09:06:39 [INFO]   File "/home/ubuntu/work/branches/neutron-gateway/.tox/func-target/lib/python3.8/site-packages/zaza/__init__.py", line 47, in _run_it
2021-04-12 09:06:39 [INFO]     return await f(*args, **kwargs)
2021-04-12 09:06:39 [INFO]   File "/home/ubuntu/work/branches/neutron-gateway/.tox/func-target/lib/python3.8/site-packages/zaza/model.py", line 736, in async_run_action
2021-04-12 09:06:39 [INFO]     raise ActionFailed(action_obj)
2021-04-12 09:06:39 [INFO] zaza.model.ActionFailed: Run of action "run-deferred-hooks" with parameters "<not-set>" on "neutron-gateway/0" failed with "Charm does not defer any hooks at present" (id=84 statu
s=failed enqueued=2021-04-12T09:05:26Z started=2021-04-12T09:05:26Z completed=2021-04-12T09:06:35Z)
2021-04-12 09:06:39 [INFO] ----------------------------------------------------------------------
2021-04-12 09:06:39 [INFO] Ran 1 test in 349.655s
2021-04-12 09:06:39 [INFO] FAILED
2021-04-12 09:06:39 [INFO]  (errors=1)
Traceback (most recent call last):
  File "/home/ubuntu/work/branches/neutron-gateway/.tox/func-target/bin/functest-test", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/work/branches/neutron-gateway/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/test.py", line 161, in main
    test(
  File "/home/ubuntu/work/branches/neutron-gateway/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/test.py", line 122, in test
    run_test_list(tests)
  File "/home/ubuntu/work/branches/neutron-gateway/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/test.py", line 111, in run_test_list
    get_test_runners()[runner](testcase, _testcase) 
  File "/home/ubuntu/work/branches/neutron-gateway/.tox/func-target/lib/python3.8/site-packages/zaza/charm_lifecycle/test.py", line 73, in run_unittest
    assert test_result.wasSuccessful(), "Test run failed"
AssertionError: Test run failed

```

**Comment by AurelienLourot** [comment]
Fixed by #554 and #555
