### ISSUE TITLE
With Juju 2.9: None does not appear to be an IPv4 or IPv6 address

### ISSUE THREAD

**Issue by AurelienLourot** [openstack-charmers/zaza-openstack-tests#642]
https://openstack-ci-reports.ubuntu.com/artifacts/f94/811942/1/check/bionic-ussuri/f94334a/

```
Traceback (most recent call last):
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-openstack-dashboard/.tox/func-target/bin/functest-run-suite", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-openstack-dashboard/.tox/func-target/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 372, in main
    test_directory=args.test_directory)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-openstack-dashboard/.tox/func-target/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 278, in func_test_runner
    force=force, test_directory=test_directory)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-openstack-dashboard/.tox/func-target/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 154, in run_env_deployment
    test_directory=test_directory)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-openstack-dashboard/.tox/func-target/lib/python3.6/site-packages/zaza/charm_lifecycle/configure.py", line 51, in configure
    run_configure_list(functions)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-openstack-dashboard/.tox/func-target/lib/python3.6/site-packages/zaza/charm_lifecycle/configure.py", line 37, in run_configure_list
    utils.get_class(func)()
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-openstack-dashboard/.tox/func-target/lib/python3.6/site-packages/zaza/openstack/charm_tests/keystone/setup.py", line 142, in add_demo_user
    _v3()
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-openstack-dashboard/.tox/func-target/lib/python3.6/site-packages/zaza/openstack/charm_tests/keystone/setup.py", line 69, in _v3
    keystone_session = openstack_utils.get_overcloud_keystone_session()
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-openstack-dashboard/.tox/func-target/lib/python3.6/site-packages/zaza/openstack/utilities/openstack.py", line 521, in get_overcloud_keystone_session
    get_overcloud_auth(model_name=model_name),
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-openstack-dashboard/.tox/func-target/lib/python3.6/site-packages/zaza/openstack/utilities/openstack.py", line 2057, in get_overcloud_auth
    address = network_utils.format_addr(address)
  File "/home/ubuntu/src/review.opendev.org/openstack/charm-openstack-dashboard/.tox/func-target/lib/python3.6/site-packages/zaza/utilities/networking.py", line 28, in format_addr
    ipaddr = ipaddress.ip_address(addr)
  File "/usr/lib/python3.6/ipaddress.py", line 54, in ip_address
    address)
ValueError: None does not appear to be an IPv4 or IPv6 address
ERROR: InvocationError for command /home/ubuntu/src/review.opendev.org/openstack/charm-openstack-dashboard/.tox/func-target/bin/functest-run-suite --keep-model --bundle bionic-ussuri (exited with code 1)
```

Probably because we use `unit-get` [in get_keystone_ip()](https://github.com/openstack-charmers/zaza-openstack-tests/blob/master/zaza/openstack/utilities/openstack.py#L2006) and get hit by [this juju bug](https://bugs.launchpad.net/juju/+bug/1910973).

**Comment by ChrisMacNaughton** [comment]
I've opened [this bug](https://github.com/juju/python-libjuju/issues/551) to track the issue in libjuju itself, as it's a bug in that library

**Comment by freyes** [comment]
There was an attempt to fix this in https://github.com/openstack-charmers/zaza/pull/468 , although it had to be reverted https://github.com/openstack-charmers/zaza/pull/471 .
