### ISSUE TITLE
Openstack series upgrade tries to pause applications that cannot be paused

### ISSUE THREAD

**Issue by Basdbruijne** [openstack-charmers/zaza-openstack-tests#704]
During openstack upgrade bionic -> focal:

```
Traceback (most recent call last):
  File "./solutions-qa-ci/bin/openstack_upgrade.py", line 147, in <module>
    main()
  File "./solutions-qa-ci/bin/openstack_upgrade.py", line 53, in main
    series_upgrader.test_200_run_series_upgrade()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/charm_tests/series_upgrade/parallel_tests.py", line 119, in test_200_run_series_upgrade
    asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/charm_tests/series_upgrade/parallel_tests.py", line 135, in wrap_coroutine_with_sem
    await coroutine
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/utilities/parallel_series_upgrade.py", line 202, in parallel_series_upgrade
    await maybe_pause_things(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/utilities/parallel_series_upgrade.py", line 525, in maybe_pause_things
    await asyncio.gather(*unit_pauses)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/utilities/parallel_series_upgrade.py", line 531, in _pause_helper
    await model.async_run_action(unit, "pause", action_params={})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/model.py", line 983, in async_run_action
    action_obj = await unit.run_action(action_name, **action_params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/juju/unit.py", line 191, in run_action
    res = await action_facade.Enqueue(actions=[client.Action(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/juju/client/facade.py", line 482, in wrapper
    reply = await f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/juju/client/_client2.py", line 244, in Enqueue
    reply = await self.rpc(msg)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/juju/client/facade.py", line 655, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/juju/client/connection.py", line 644, in rpc
    raise errors.JujuError(err_results)
juju.errors.JujuError: ['action "pause" not defined on unit "filebeat/58"']
```

We observed the same problem for landscape-client, logrotated, public-policy-routing and telegraf. 
Zaza should check if the unit has a pause action before pausing it.

**Comment by ajkavanagh** [comment]
Yes, that would probably be a good thing to do.
