### ISSUE TITLE
Openstack series upgrade fails if a machine is already upgraded

### ISSUE THREAD

**Issue by Basdbruijne** [openstack-charmers/zaza-openstack-tests#705]
When doing the Openstack series upgrade on a deployment that has been partially upgraded already, zaza fails on:

```
INFO:root:About to call '['juju', 'set-series', '-m', 'openstack', 'rabbitmq-server', 'focal']'
WARNING:root:STDOUT: 
WARNING:root:STDERR: ERROR machine 4/lxd/1 already at series focal
Traceback (most recent call last):
  File "./solutions-qa-ci/bin/openstack_upgrade.py", line 147, in <module>
    main()
  File "./solutions-qa-ci/bin/openstack_upgrade.py", line 53, in main
    series_upgrader.test_200_run_series_upgrade()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/charm_tests/series_upgrade/parallel_tests.py", line 119, in test_200_run_series_upgrade
    asyncio.get_event_loop().run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/charm_tests/series_upgrade/parallel_tests.py", line 135, in wrap_coroutine_with_sem
    await coroutine
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/utilities/parallel_series_upgrade.py", line 333, in serial_series_upgrade
    await prepare_series_upgrade(leader_machine, to_series=to_series)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/utilities/parallel_series_upgrade.py", line 578, in prepare_series_upgrade
    await series_upgrade_utils.async_prepare_series_upgrade(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/utilities/series_upgrade.py", line 749, in async_prepare_series_upgrade
    await os_utils.check_call(cmd)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/utilities/generic.py", line 394, in check_call
    raise subprocess.CalledProcessError(proc.returncode, cmd)
subprocess.CalledProcessError: Command '['juju', 'upgrade-series', '-m', 'openstack', '4/lxd/1', 'prepare', 'focal', '--yes']' returned non-zero exit status 1.
```

It would be nice if Zaza could check the machine series before upgrading, and skip the upgrade if the machine is already upgraded.

**Comment by ajkavanagh** [comment]
It's possible to do this, but the 'ethos' is is not really to handle partially upgraded systems.  However, I can see why this would be a good feature.  Adding to wishlist.
