### ISSUE TITLE
Openstack-upgrade times out waiting for unit to change openstack source

### ISSUE THREAD

**Issue by Basdbruijne** [openstack-charmers/zaza-openstack-tests#753]
In testrun:
https://solutions.qa.canonical.com/testruns/testRun/1163f05a-fbe4-4693-9736-7cf93db208c2

With console:
https://oil-jenkins.canonical.com/job/fce_openstackupgrade/11//console

Openstack-upgrade dies on timeout setting source:
```
Traceback (most recent call last):
  File "./solutions-qa-ci/bin/openstack_upgrade.py", line 147, in <module>
    main()
  File "./solutions-qa-ci/bin/openstack_upgrade.py", line 63, in main
    openstack_upgrade.run_upgrade_tests(f"cloud:{series}-{upgrade_version}")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/utilities/openstack_upgrade.py", line 354, in run_upgrade_tests
    run_upgrade_on_apps(apps, new_source, model_name=model_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/utilities/openstack_upgrade.py", line 329, in run_upgrade_on_apps
    run_all_in_one_upgrades(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/openstack/utilities/openstack_upgrade.py", line 301, in run_all_in_one_upgrades
    zaza.model.block_until_all_units_idle()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/__init__.py", line 108, in _wrapper
    return run(_run_it())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/__init__.py", line 93, in run
    return task.result()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/__init__.py", line 107, in _run_it
    return await f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/model.py", line 1630, in async_block_until_all_units_idle
    await block_until_auto_reconnect_model(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/zaza/model.py", line 318, in block_until_auto_reconnect_model
    await asyncio.wait_for(_block(), timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```

Because of [LP: #1960030](https://bugs.launchpad.net/charm-keystone/+bug/1960030), we rerun all the openstack upgrades when they fail. We can see in this case that on the second run, `mysql-innodb-cluster` is skipped because its already on the new source. This leads me to think that it is a zaza bug.

All the occurrences can be found here:
https://solutions.qa.canonical.com/bugs/bugs/bug/1969364

Crashdumps can be found by going to the testrun uuid and then following the link on the bottom of the page, here is one:
https://oil-jenkins.canonical.com/artifacts/1163f05a-fbe4-4693-9736-7cf93db208c2/index.html

**Comment by ajkavanagh** [comment]
The z-o-t upgrade scripts aren't idempotent and thus don't support being "restarted", as the reason an upgrade failed may actually leave the system in a 'broken' state.  Thus if this bug only occurs on a 2nd of subsequent run on the same system-under-test, then I'm tempted to close this as a wont-fix as it would be extremely difficult to code checks for every scenario that a partially upgraded system can get into.

**Comment by Basdbruijne** [comment]
In all the 3 cases this happens both before and after the restart, which can be seen in the [console output](https://oil-jenkins.canonical.com/job/fce_openstackupgrade/9//consoleFull).

I mentioned the restart because the information it provides leads me to believe that this is a bug in zaza, rather than in `charm-mysql-innodb-cluster`, even though all 3 occurrences fail on changing the source on the `mysql-innodb-cluster` application.

**Comment by ajkavanagh** [comment]
It might be useful to set logging to debug so that you can see where it's getting to?

**Comment by Basdbruijne** [comment]
Good idea :)
I will let you know if we see this again with the logging set to debug.

**Comment by Basdbruijne** [comment]
I think I have found the cause of this issue. Zaza waits for all units to be idle but SQA sometimes has applications that are not fully configured at the end of the deployment. An example of this is `landscape-client`, which says in maintenance mode.

Rather than having zaza figure out which applications need to be waited for, I think its better if we remove the configured applications from the deployment before doing the upgrade.
