### ISSUE TITLE
zaza.openstack.charm_tests.neutron.setup.basic_overcloud_network: ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by fnordahl** [openstack-charmers/zaza-openstack-tests#78]
```
2019-10-02 09:21:06 [INFO] Attaching additional port to instance, connected to net id: e254b5c3-fe0a-4cda-b84c-5695de7d4033
2019-10-02 09:21:14 [INFO] Trying to get mac address from port:38c7d263-07df-48ad-9d78-4aeb7772f2fc
Traceback (most recent call last):
  File "/home/ubuntu/src/charm-octavia/build/builds/octavia/.tox/func-smoke/bin/functest-run-suite", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/src/charm-octavia/build/builds/octavia/.tox/func-smoke/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 162, in main
    bundle=args.bundle)
  File "/home/ubuntu/src/charm-octavia/build/builds/octavia/.tox/func-smoke/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 107, in func_test_runner
    run_env_deployment(env_deployment, keep_model=preserve_model)
  File "/home/ubuntu/src/charm-octavia/build/builds/octavia/.tox/func-smoke/lib/python3.6/site-packages/zaza/charm_lifecycle/func_test_runner.py", line 58, in run_env_deployment
    config_steps.get(deployment.model_alias, []))
  File "/home/ubuntu/src/charm-octavia/build/builds/octavia/.tox/func-smoke/lib/python3.6/site-packages/zaza/charm_lifecycle/configure.py", line 48, in configure
    run_configure_list(functions)
  File "/home/ubuntu/src/charm-octavia/build/builds/octavia/.tox/func-smoke/lib/python3.6/site-packages/zaza/charm_lifecycle/configure.py", line 37, in run_configure_list
    utils.get_class(func)()
  File "/home/ubuntu/src/charm-octavia/build/builds/octavia/.tox/func-smoke/lib/python3.6/site-packages/zaza/openstack/charm_tests/neutron/setup.py", line 89, in basic_overcloud_network
    keystone_session=undercloud_ks_sess)
  File "/home/ubuntu/src/charm-octavia/build/builds/octavia/.tox/func-smoke/lib/python3.6/site-packages/zaza/openstack/configure/network.py", line 231, in setup_gateway_ext_port
    add_dataport_to_netplan=add_dataport_to_netplan)
  File "/home/ubuntu/src/charm-octavia/build/builds/octavia/.tox/func-smoke/lib/python3.6/site-packages/zaza/openstack/utilities/openstack.py", line 615, in configure_gateway_ext_port
    dvr_mode=dvr_mode)
  File "/home/ubuntu/src/charm-octavia/build/builds/octavia/.tox/func-smoke/lib/python3.6/site-packages/zaza/openstack/utilities/openstack.py", line 520, in add_interface_to_netplan
    server_name, application_name)
  File "/home/ubuntu/src/charm-octavia/build/builds/octavia/.tox/func-smoke/lib/python3.6/site-packages/zaza/openstack/utilities/juju.py", line 113, in get_unit_name_from_host_name
    for u in model.get_units(application_name=application)
  File "/home/ubuntu/src/charm-octavia/build/builds/octavia/.tox/func-smoke/lib/python3.6/site-packages/zaza/openstack/utilities/juju.py", line 114, in <listcomp>
    if int(u.data['machine-id']) == int(machine_number)]
ValueError: invalid literal for int() with base 10: ''
ERROR: InvocationError: '/home/ubuntu/src/charm-octavia/build/builds/octavia/.tox/func-smoke/bin/functest-run-suite --keep-model --smoke'
______________________________________________________________________________ summary _______________________________________________________________________________
ERROR:   func-smoke: commands failed
```

**Comment by andrewdmcleod** [comment]
this was triggered by:

    unit_name = juju_utils.get_unit_name_from_host_name(
        server_name, application_name)

Not entirely sure why this would have failed, perhaps there was a problem with the deployment?

**Comment by andrewdmcleod** [comment]
the problem is that subordinates do not have a unit ID. suggest that we make a note and do not add the port to netplan for dvr instances.

**Comment by fnordahl** [comment]
Fixed by https://github.com/openstack-charmers/zaza-openstack-tests/pull/79
