### ISSUE TITLE
series upgrade of percona skipped Ubuntu upgrade

### ISSUE THREAD

**Issue by gnuoy** [openstack-charmers/zaza-openstack-tests#81]
In a run of series upgrade, the series upgrade part appeared to be skipped and the the post-upgrade hook failed.

```
2019-10-05 09:41:37 INFO juju-log Unit is ready
2019-10-05 09:44:42 DEBUG pre-series-upgrade inactive
2019-10-05 09:44:42 DEBUG pre-series-upgrade inactive
2019-10-05 09:44:42 DEBUG pre-series-upgrade active
2019-10-05 09:44:46 DEBUG pre-series-upgrade mysql.service is not a native service, redirecting to systemd-sysv-install
2019-10-05 09:44:46 DEBUG pre-series-upgrade Executing /lib/systemd/systemd-sysv-install disable mysql
2019-10-05 09:44:46 DEBUG pre-series-upgrade insserv: warning: current start runlevel(s) (empty) of script `mysql' overrides LSB defaults (2 3 4 5).
2019-10-05 09:44:46 DEBUG pre-series-upgrade insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `mysql' overrides LSB defaults (0 1 6).
2019-10-05 09:44:46 DEBUG pre-series-upgrade Created symlink from /etc/systemd/system/mysql.service to /dev/null.
2019-10-05 09:44:52 DEBUG pre-series-upgrade inactive
2019-10-05 09:44:53 DEBUG juju-log Writing file /etc/mysql/percona-xtradb-cluster.conf.d/mysqld.cnf root:root 444
2019-10-05 09:44:53 DEBUG pre-series-upgrade inactive
2019-10-05 09:44:53 DEBUG pre-series-upgrade inactive
2019-10-05 09:45:22 INFO juju.cmd supercommand.go:57 running jujud [2.6.10 gc go1.10.4]
2019-10-05 09:45:22 DEBUG juju.cmd supercommand.go:58   args: []string{"/var/lib/juju/tools/unit-mysql-1/jujud", "unit", "--data-dir", "/var/lib/juju", "--unit-name", "mysql/1", "--debug"}
2019-10-05 09:45:22 DEBUG juju.agent agent.go:545 read agent config, format "2.0"
2019-10-05 09:45:22 INFO juju.cmd.jujud agent.go:133 setting logging config to "<root>=WARNING;unit=DEBUG"
2019-10-05 09:46:17 INFO juju-log Making dir /var/run/mysqld mysql:mysql 755
2019-10-05 09:46:17 INFO juju-log Installing ['percona-xtradb-cluster-server'] with options: ['--option=Dpkg::Options::=--force-confold']
2019-10-05 09:46:18 DEBUG post-series-upgrade Reading package lists...
2019-10-05 09:46:18 DEBUG post-series-upgrade Building dependency tree...
2019-10-05 09:46:18 DEBUG post-series-upgrade Reading state information...
2019-10-05 09:46:18 DEBUG post-series-upgrade percona-xtradb-cluster-server is already the newest version (5.6.37-26.21-0ubuntu0.16.04.2).
2019-10-05 09:46:18 DEBUG post-series-upgrade 0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
2019-10-05 09:46:18 INFO juju-log Starting mysqld --wsrep-provider='none' and waiting ...
2019-10-05 09:46:18 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-05 09:46:28 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-05 09:46:38 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-05 09:46:48 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-05 09:46:58 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-05 09:47:09 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-05 09:47:19 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-05 09:47:29 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-05 09:47:39 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-05 09:47:49 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-05 09:47:59 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-05 09:48:09 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-05 09:48:19 DEBUG post-series-upgrade Traceback (most recent call last):
2019-10-05 09:48:19 DEBUG post-series-upgrade   File "/var/lib/juju/agents/unit-mysql-1/charm/hooks/post-series-upgrade", line 1132, in <module>
2019-10-05 09:48:19 DEBUG post-series-upgrade     main()
2019-10-05 09:48:19 DEBUG post-series-upgrade   File "/var/lib/juju/agents/unit-mysql-1/charm/hooks/post-series-upgrade", line 1122, in main
2019-10-05 09:48:19 DEBUG post-series-upgrade     hooks.execute(sys.argv)
2019-10-05 09:48:19 DEBUG post-series-upgrade   File "/var/lib/juju/agents/unit-mysql-1/charm/charmhelpers/core/hookenv.py", line 914, in execute
2019-10-05 09:48:19 DEBUG post-series-upgrade     self._hooks[hook_name]()
2019-10-05 09:48:19 DEBUG post-series-upgrade   File "/var/lib/juju/agents/unit-mysql-1/charm/hooks/post-series-upgrade", line 434, in series_upgrade
2019-10-05 09:48:19 DEBUG post-series-upgrade     check_for_socket(MYSQL_SOCKET, exists=True)
2019-10-05 09:48:19 DEBUG post-series-upgrade   File "/var/lib/juju/agents/unit-mysql-1/charm/hooks/percona_utils.py", line 1204, in check_for_socket
2019-10-05 09:48:19 DEBUG post-series-upgrade     .format(file_name, attempts))
2019-10-05 09:48:19 DEBUG post-series-upgrade Exception: Socket /var/run/mysqld/mysqld.sock not found after 12 attempts.
2019-10-05 09:48:19 ERROR juju.worker.uniter.operation runhook.go:132 hook "post-series-upgrade" failed: exit status 1
```

**Comment by gnuoy** [comment]
Note: This bug relates to the fact that the series upgrade did not happen which can be seen from the fact that the post-series-upgrade hook runs only 60s after the pre-hooks. The stacktrace at the end is Issue #86 .

I think the issue the reason it was skipped was:
```
 2019-10-10 10:18:30 [INFO] Upgrading mysql/0
Checking for a new Ubuntu release
Please install all available updates for your release before upgrading.
Connection to 10.5.0.6 closed.
2019-10-10 10:18:33 [WARNING] Failed do-release-upgrade for mysql/0
```
