### ISSUE TITLE
post-series-upgrade hook fails for percona

### ISSUE THREAD

**Issue by gnuoy** [openstack-charmers/zaza-openstack-tests#86]
When mysql has been upgraded the port upgrade hook faile with

```
2019-10-10 10:13:31 INFO juju-log Installing ['percona-xtradb-cluster-server'] with options: ['--option=Dpkg::Options::=--force-confold']
2019-10-10 10:13:31 DEBUG post-series-upgrade Reading package lists...
2019-10-10 10:13:31 DEBUG post-series-upgrade Building dependency tree...
2019-10-10 10:13:31 DEBUG post-series-upgrade Reading state information...
2019-10-10 10:13:31 DEBUG post-series-upgrade percona-xtradb-cluster-server is already the newest version (5.6.37-26.21-0ubuntu0.16.04.2).
2019-10-10 10:13:31 DEBUG post-series-upgrade 0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.
2019-10-10 10:13:31 INFO juju-log Starting mysqld --wsrep-provider='none' and waiting ...
2019-10-10 10:13:32 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-10 10:13:42 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-10 10:13:52 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-10 10:14:02 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-10 10:14:13 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-10 10:14:23 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-10 10:14:33 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-10 10:14:43 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-10 10:14:53 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-10 10:15:03 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-10 10:15:13 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-10 10:15:23 DEBUG juju-log /var/run/mysqld/mysqld.sock file is not yet ihe correct state retrying. Check for exists=True
2019-10-10 10:15:33 DEBUG post-series-upgrade Traceback (most recent call last):
2019-10-10 10:15:33 DEBUG post-series-upgrade   File "/var/lib/juju/agents/unit-mysql-0/charm/hooks/post-series-upgrade", line 1132, in <module>
2019-10-10 10:15:33 DEBUG post-series-upgrade     main()
2019-10-10 10:15:33 DEBUG post-series-upgrade   File "/var/lib/juju/agents/unit-mysql-0/charm/hooks/post-series-upgrade", line 1122, in main
2019-10-10 10:15:33 DEBUG post-series-upgrade     hooks.execute(sys.argv)
2019-10-10 10:15:33 DEBUG post-series-upgrade   File "/var/lib/juju/agents/unit-mysql-0/charm/charmhelpers/core/hookenv.py", line 914, in execute
2019-10-10 10:15:33 DEBUG post-series-upgrade     self._hooks[hook_name]()
2019-10-10 10:15:33 DEBUG post-series-upgrade   File "/var/lib/juju/agents/unit-mysql-0/charm/hooks/post-series-upgrade", line 434, in series_upgrade
2019-10-10 10:15:33 DEBUG post-series-upgrade     check_for_socket(MYSQL_SOCKET, exists=True)
2019-10-10 10:15:33 DEBUG post-series-upgrade   File "/var/lib/juju/agents/unit-mysql-0/charm/hooks/percona_utils.py", line 1204, in check_for_socket
2019-10-10 10:15:33 DEBUG post-series-upgrade     .format(file_name, attempts))
2019-10-10 10:15:33 DEBUG post-series-upgrade Exception: Socket /var/run/mysqld/mysqld.sock not found after 12 attempts.
2019-10-10 10:15:33 ERROR juju.worker.uniter.operation runhook.go:132 hook "post-series-upgrade" failed: exit status 1
```

**Comment by gnuoy** [comment]
I think this is due to Issue #81 Because the percona package upgrade did not happen the subsequent post upgrade tasks are invalid
