### ISSUE TITLE
Designate series upgrade fails

### ISSUE THREAD

**Issue by gnuoy** [openstack-charmers/zaza-openstack-tests#88]
```
17:21:00 2019-10-10 17:20:58 [INFO] Prepare series upgrade on 10
17:21:00 ERROR unit designate/1 is not ready to start a series upgrade; its agent status is: "executing" running action juju-run
17:21:00 Traceback (most recent call last):
17:21:00   File "/tmp/tmp.PKzDYw8VZG/mojo-openstack-specs/xenial/osci-mojo/spec/specs/full_stack/next_series_upgrade/queens/series_upgrade.py", line 42, in <module>
17:21:00     sys.exit(series_upgrade_test.test_200_run_series_upgrade())
17:21:00   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/openstack/charm_tests/series_upgrade/tests.py", line 99, in test_200_run_series_upgrade
17:21:00     files=self.files)
17:21:00   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/openstack/utilities/generic.py", line 313, in series_upgrade_application
17:21:00     files=files)
17:21:00   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/openstack/utilities/generic.py", line 372, in series_upgrade
17:21:00     model.prepare_series_upgrade(machine_num, to_series=to_series)
17:21:00   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/model.py", line 1517, in prepare_series_upgrade
17:21:00     subprocess.check_call(cmd)
17:21:00   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
17:21:00     raise CalledProcessError(retcode, cmd)
17:21:00 subprocess.CalledProcessError: Command '['juju', 'upgrade-series', '-m', 'auto-osci-sv13', '10', 'prepare', 'bionic', '--yes']' returned non-zero exit status 1
```

**Comment by gnuoy** [comment]
More details: https://paste.ubuntu.com/p/sptgKYwchq/

**Comment by ajkavanagh** [comment]
Hit this again.  Going to try to sort it out.


```
2020-09-14 21:32:07 [INFO] Updating existing packages 41
2020-09-14 21:32:07 [INFO] About to call '['juju', 'run', '--machine=41', 'yes | sudo DEBIAN_FRONTEND=noninteractive apt-get --assume-yes -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" dist-upgrade']'
2020-09-14 21:32:08 [INFO] Preparing series upgrade for: 2
2020-09-14 21:32:08 [INFO] About to call '['juju', 'upgrade-series', '-m', 'mojo', '2', 'prepare', 'bionic', '--yes']'
2020-09-14 21:32:08 [INFO] Preparing series upgrade for: 1
2020-09-14 21:32:08 [INFO] About to call '['juju', 'upgrade-series', '-m', 'mojo', '1', 'prepare', 'bionic', '--yes']'
2020-09-14 21:32:10 [WARNING] STDOUT:
2020-09-14 21:32:10 [WARNING] STDERR: ERROR unit aodh-hacluster/0 is not ready to start a series upgrade; its agent status is: "executing" running hanode-relation-changed hook

Traceback (most recent call last):
  File "/srv/mojo/openstack/xenial/default_20201314_171352/spec/specs/full_stack/next_series_upgrade/queens/series_upgrade.py", line 42, in <module>
    sys.exit(series_upgrade_test.test_200_run_series_upgrade())
  File "/home/ubuntu/git/github.com/openstack-charmers/zaza-openstack-tests/zaza/openstack/charm_tests/series_upgrade/parallel_tests.py", line 106, in test_200_run_series_upgrade
    asyncio.gather(*upgrade_functions))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/ubuntu/git/github.com/openstack-charmers/zaza-openstack-tests/zaza/openstack/utilities/parallel_series_upgrade.py", line 219, in parallel_series_upgrade
    await asyncio.gather(*prepare_group)
  File "/home/ubuntu/git/github.com/openstack-charmers/zaza-openstack-tests/zaza/openstack/utilities/parallel_series_upgrade.py", line 553, in prepare_series_upgrade
    machine, to_series=to_series)
  File "/home/ubuntu/git/github.com/openstack-charmers/zaza-openstack-tests/zaza/openstack/utilities/series_upgrade.py", line 749, in async_prepare_series_upgrade
    await os_utils.check_call(cmd)
  File "/home/ubuntu/git/github.com/openstack-charmers/zaza-openstack-tests/zaza/openstack/utilities/generic.py", line 393, in check_call
    raise subprocess.CalledProcessError(proc.returncode, cmd)
subprocess.CalledProcessError: Command '['juju', 'upgrade-series', '-m', 'mojo', '2', 'prepare', 'bionic', '--yes']' returned non-zero exit status 1.
```
