### ISSUE TITLE
series upgrade hangs for tempest charm

### ISSUE THREAD

**Issue by gnuoy** [openstack-charmers/zaza-openstack-tests#94]
Series upgrade script appears to hang when upgrading the tempest charm. The upgrade to bionic appears to work but the upgrade is never marked as complete (via "juju upgrade-series X complete")

```
03:17:14 2019-10-13 03:16:50 [INFO] Reboot tempest/0
03:17:14 Connection to 172.17.107.35 closed by remote host.
03:17:14 2019-10-13 03:16:52 [INFO] Command '['juju', 'ssh', 'tempest/0', 'sudo', 'reboot', '&&', 'exit']' returned non-zero exit status 255
03:17:14 2019-10-13 03:16:52 [INFO] Waiting for workload status 'blocked' on tempest/0
03:17:14 2019-10-13 03:17:10 [INFO] Waiting for model idleness
03:17:14 2019-10-13 03:17:11 [INFO] Set origin on tempest
03:17:14 2019-10-13 03:17:11 [INFO] Set origin on tempest to openstack-origin
03:17:14 Traceback (most recent call last):
03:17:14   File "/tmp/tmp.SonXZG2Dxz/mojo-openstack-specs/xenial/osci-mojo/spec/specs/full_stack/next_series_upgrade/queens/series_upgrade.py", line 42, in <module>
03:17:14     sys.exit(series_upgrade_test.test_200_run_series_upgrade())
03:17:14   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/openstack/charm_tests/series_upgrade/tests.py", line 101, in test_200_run_series_upgrade
03:17:14     files=self.files)
03:17:14   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/openstack/utilities/generic.py", line 313, in series_upgrade_application
03:17:14     files=files)
03:17:14   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/openstack/utilities/generic.py", line 392, in series_upgrade
03:17:14     set_origin(application, origin)
03:17:14   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/openstack/utilities/generic.py", line 421, in set_origin
03:17:14     model.set_application_config(application, {origin: pocket})
03:17:14   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/__init__.py", line 48, in _wrapper
03:17:14     return run(_run_it())
03:17:14   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/__init__.py", line 36, in run
03:17:14     return task.result()
03:17:14   File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
03:17:14     raise self._exception
03:17:14   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
03:17:14     result = coro.send(None)
03:17:14   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/__init__.py", line 47, in _run_it
03:17:14     return await f(*args, **kwargs)
03:17:14   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/zaza/model.py", line 498, in async_set_application_config
03:17:14     .set_config(configuration))
03:17:14   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/juju/application.py", line 383, in set_config
03:17:14     return await app_facade.Set(application=self.name, options=config)
03:17:14   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/juju/client/facade.py", line 472, in wrapper
03:17:14     reply = await f(*args, **kwargs)
03:17:14   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/juju/client/_client8.py", line 1124, in Set
03:17:14     reply = await self.rpc(msg)
03:17:14   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/juju/client/facade.py", line 608, in rpc
03:17:14     result = await self.connection.rpc(msg, encoder=TypeEncoder)
03:17:14   File "/var/lib/jenkins/tools/0/charm-test-infra/.tox/clients/lib/python3.5/site-packages/juju/client/connection.py", line 455, in rpc
03:17:14     raise errors.JujuAPIError(result)
03:17:14 juju.errors.JujuAPIError: unknown option "openstack-origin"
03:17:14 
03:17:14 
03:17:14  change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:07:06.510765898Z', 'version': ''}
03:17:14 2019-10-12 19:07:33 [DEBUG] deployer.env:  Delta unit: nova-compute/1 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:01:47.632721293Z', 'version': ''}
03:17:14 2019-10-12 19:07:52 [DEBUG] deployer.env:  Delta unit: nova-compute/1 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:01:47.632721293Z', 'version': ''}
03:17:14 2019-10-12 19:07:52 [DEBUG] deployer.env:  Delta application: nova-cloud-controller change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:07:50.371163822Z', 'version': ''}
03:17:14 2019-10-12 19:07:52 [DEBUG] deployer.env:  Delta unit: nova-cloud-controller/0 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:07:50.371163822Z', 'version': ''}
03:17:14 2019-10-12 19:07:52 [DEBUG] deployer.env:  Delta unit: nova-cloud-controller/0 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:07:50.371163822Z', 'version': ''}
03:17:14 2019-10-12 19:07:52 [DEBUG] deployer.env:  Delta unit: nova-compute/0 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:02:38.338923805Z', 'version': ''}
03:17:14 2019-10-12 19:07:52 [DEBUG] deployer.env:  Delta unit: neutron-gateway/0 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:00:04.230844154Z', 'version': ''}
03:17:14 2019-10-12 19:07:52 [DEBUG] deployer.env:  Delta unit: designate/0 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:07:06.510765898Z', 'version': ''}
03:17:14 2019-10-12 19:07:52 [DEBUG] deployer.env:  Delta unit: designate/2 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:06:53.562023255Z', 'version': ''}
03:17:14 2019-10-12 19:07:53 [DEBUG] deployer.env:  Delta unit: nova-compute/2 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:03:18.074289245Z', 'version': ''}
03:17:14 2019-10-12 19:08:02 [DEBUG] deployer.env:  Delta unit: designate/2 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:06:53.562023255Z', 'version': ''}
03:17:14 2019-10-12 19:08:02 [DEBUG] deployer.env:  Delta unit: designate/0 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:07:06.510765898Z', 'version': ''}
03:17:14 2019-10-12 19:08:02 [DEBUG] deployer.env:  Delta unit: nova-compute/1 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:01:47.632721293Z', 'version': ''}
03:17:14 2019-10-12 19:08:10 [DEBUG] deployer.env:  Delta unit: neutron-gateway/0 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:00:04.230844154Z', 'version': ''}
03:17:14 2019-10-12 19:08:10 [DEBUG] deployer.env:  Delta unit: nova-compute/0 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:02:38.338923805Z', 'version': ''}
03:17:14 2019-10-12 19:08:19 [DEBUG] deployer.env:  Delta unit: nova-compute/2 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:03:18.074289245Z', 'version': ''}
03:17:14 2019-10-12 19:08:19 [DEBUG] deployer.env:  Delta unit: nova-compute/1 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:01:47.632721293Z', 'version': ''}
03:17:14 2019-10-12 19:09:08 [DEBUG] deployer.env:  Delta unit: designate/2 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:06:53.562023255Z', 'version': ''}
03:17:14 2019-10-12 19:09:08 [DEBUG] deployer.env:  Delta unit: designate/0 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:07:06.510765898Z', 'version': ''}
03:17:14 2019-10-12 19:09:41 [DEBUG] deployer.env:  Delta unit: designate/0 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:07:06.510765898Z', 'version': ''}
03:17:14 2019-10-12 19:09:41 [DEBUG] deployer.env:  Delta unit: designate/2 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:06:53.562023255Z', 'version': ''}
03:17:14 2019-10-12 19:10:24 [DEBUG] deployer.env:  Delta unit: designate/2 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:06:53.562023255Z', 'version': ''}
03:17:14 2019-10-12 19:10:24 [DEBUG] deployer.env:  Delta unit: designate/0 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:07:06.510765898Z', 'version': ''}
03:17:14 2019-10-12 19:10:47 [DEBUG] deployer.env:  Delta application: designate change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:07:06.510765898Z', 'version': ''}
03:17:14 2019-10-12 19:10:47 [DEBUG] deployer.env:  Delta unit: designate/1 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:10:43.430562369Z', 'version': ''}
03:17:14 2019-10-12 19:10:47 [DEBUG] deployer.env:  Delta unit: designate/1 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:10:43.430562369Z', 'version': ''}
03:17:14 2019-10-12 19:11:01 [DEBUG] deployer.env:  Delta unit: designate/2 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:06:53.562023255Z', 'version': ''}
03:17:14 2019-10-12 19:11:01 [DEBUG] deployer.env:  Delta unit: designate/0 change:{'current': 'active', 'message': 'Unit is ready', 'since': '2019-10-12T19:07:06.510765898Z', 'version': ''}
03:17:14 2019-10-12 19:11:01 [INFO] deployer.cli: Deployment complete in 1718.59 seconds
03:17:14 + [[ 1 != \0 ]]
03:17:14 + echo ' ! Mojo run manifest failed.'
03:17:14  ! Mojo run manifest failed.
03:17:14 + touch /var/lib/jenkins/workspace/mojo_runner/fyi-.-mojo-run.failed
03:17:14 + set +x
03:17:14 ====>  end of mojo's run  <=======================
03:17:17 Model           Controller      Cloud/Region             Version  SLA          Timestamp
03:17:17 auto-osci-sv07  auto-osci-sv07  serverstack/serverstack  2.6.10   unsupported  03:17:15Z
03:17:17 
03:17:17 App                    Version      Status   Scale  Charm                  Store  Rev  OS      Notes
03:17:17 aodh                   6.0.1        active       1  aodh                   local    0  ubuntu  
03:17:17 ceilometer             10.0.1       active       1  ceilometer             local    0  ubuntu  
03:17:17 ceilometer-agent       10.0.1       active       3  ceilometer-agent       local    0  ubuntu  
03:17:17 ceph-mon               12.2.12      active       3  ceph-mon               local    0  ubuntu  
03:17:17 ceph-osd               12.2.12      active       3  ceph-osd               local   15  ubuntu  
03:17:17 cinder                 12.0.7       active       1  cinder                 local  136  ubuntu  
03:17:17 cinder-ceph            12.0.7       active       1  cinder-ceph            local    2  ubuntu  
03:17:17 designate              6.0.1        active       3  designate              local    0  ubuntu  
03:17:17 designate-bind         9.11.3+dfsg  active       3  designate-bind         local    0  ubuntu  
03:17:17 designate-hacluster                 active       3  hacluster              local    0  ubuntu  
03:17:17 glance                 16.0.1       active       1  glance                 local  150  ubuntu  
03:17:17 gnocchi                4.2.5        active       1  gnocchi                local    0  ubuntu  
03:17:17 heat                   10.0.2       active       1  heat                   local   12  ubuntu  
03:17:17 keystone               13.0.2       active       1  keystone               local    0  ubuntu  
03:17:17 memcached                           active       1  memcached              local   69  ubuntu  
03:17:17 mysql                  5.7.20       active       1  percona-cluster        local   45  ubuntu  
03:17:17 neutron-api            12.0.6       active       1  neutron-api            local    0  ubuntu  
03:17:17 neutron-gateway        12.0.6       active       1  neutron-gateway        local   64  ubuntu  
03:17:17 neutron-openvswitch    12.0.6       active       3  neutron-openvswitch    local    0  ubuntu  
03:17:17 nova-cloud-controller  17.0.10      active       1  nova-cloud-controller  local  501  ubuntu  
03:17:17 nova-compute           17.0.10      active       3  nova-compute           local  133  ubuntu  
03:17:17 openstack-dashboard    13.0.2       active       1  openstack-dashboard    local   32  ubuntu  
03:17:17 rabbitmq-server        3.6.10       active       1  rabbitmq-server        local  150  ubuntu  
03:17:17 swift-proxy            2.17.1       active       1  swift-proxy            local  147  ubuntu  
03:17:17 swift-storage-z1       2.17.1       active       1  swift-storage          local   90  ubuntu  
03:17:17 swift-storage-z2       2.17.1       active       1  swift-storage          local   91  ubuntu  
03:17:17 swift-storage-z3       2.17.1       active       1  swift-storage          local   92  ubuntu  
03:17:17 tempest                2.7.4        blocked      1  tempest                local    0  ubuntu  
03:17:17 
03:17:17 Unit                      Workload  Agent  Machine  Public address  Ports              Message
03:17:17 aodh/0*                   active    idle   0        172.17.107.5    8042/tcp           Unit is ready
03:17:17 ceilometer/0*             active    idle   1        172.17.107.27                      Unit is ready
03:17:17 ceph-mon/0*               active    idle   2        172.17.107.6                       Unit is ready and clustered
03:17:17 ceph-mon/1                active    idle   3        172.17.107.20                      Unit is ready and clustered
03:17:17 ceph-mon/2                active    idle   4        172.17.107.14                      Unit is ready and clustered
03:17:17 ceph-osd/0                active    idle   5        172.17.107.31                      Unit is ready (1 OSD)
03:17:17 ceph-osd/1                active    idle   6        172.17.107.30                      Unit is ready (1 OSD)
03:17:17 ceph-osd/2*               active    idle   7        172.17.107.32                      Unit is ready (1 OSD)
03:17:17 cinder/0*                 active    idle   8        172.17.107.10   8776/tcp           Unit is ready
03:17:17   cinder-ceph/0*          active    idle            172.17.107.10                      Unit is ready
03:17:17 designate-bind/0*         active    idle   12       172.17.107.37                      Unit is ready
03:17:17 designate-bind/1          active    idle   13       172.17.107.9                       Unit is ready
03:17:17 designate-bind/2          active    idle   14       172.17.107.12                      Unit is ready
03:17:17 designate/0               active    idle   9        172.17.107.18   9001/tcp           Unit is ready
03:17:17   designate-hacluster/2   active    idle            172.17.107.18                      Unit is ready and clustered
03:17:17 designate/1*              active    idle   10       172.17.107.3    9001/tcp           Unit is ready
03:17:17   designate-hacluster/1*  active    idle            172.17.107.3                       Unit is ready and clustered
03:17:17 designate/2               active    idle   11       172.17.107.11   9001/tcp           Unit is ready
03:17:17   designate-hacluster/0   active    idle            172.17.107.11                      Unit is ready and clustered
03:17:17 glance/0*                 active    idle   15       172.17.107.7    9292/tcp           Unit is ready
03:17:17 gnocchi/0*                active    idle   16       172.17.107.4    8041/tcp           Unit is ready
03:17:17 heat/0*                   active    idle   17       172.17.107.8    8000/tcp,8004/tcp  Unit is ready
03:17:17 keystone/0*               active    idle   18       172.17.107.22   5000/tcp           Unit is ready
03:17:17 memcached/0*              active    idle   19       172.17.107.34   11211/tcp          Unit is ready
03:17:17 mysql/0*                  active    idle   20       172.17.107.47   3306/tcp           Unit is ready
03:17:17 neutron-api/0*            active    idle   21       172.17.107.24   9696/tcp           Unit is ready
03:17:17 neutron-gateway/0*        active    idle   22       172.17.107.25                      Unit is ready
03:17:17 nova-cloud-controller/0*  active    idle   23       172.17.107.43   8774/tcp,8778/tcp  Unit is ready
03:17:17 nova-compute/0            active    idle   24       172.17.107.42                      Unit is ready
03:17:17   ceilometer-agent/1*     active    idle            172.17.107.42                      Unit is ready
03:17:17   neutron-openvswitch/1   active    idle            172.17.107.42                      Unit is ready
03:17:17 nova-compute/1            active    idle   25       172.17.107.28                      Unit is ready
03:17:17   ceilometer-agent/2      active    idle            172.17.107.28                      Unit is ready
03:17:17   neutron-openvswitch/2   active    idle            172.17.107.28                      Unit is ready
03:17:17 nova-compute/2*           active    idle   26       172.17.107.16                      Unit is ready
03:17:17   ceilometer-agent/0      active    idle            172.17.107.16                      Unit is ready
03:17:17   neutron-openvswitch/0*  active    idle            172.17.107.16                      Unit is ready
03:17:17 openstack-dashboard/0*    active    idle   27       172.17.107.50   80/tcp,443/tcp     Unit is ready
03:17:17 rabbitmq-server/0*        active    idle   28       172.17.107.15   5672/tcp           Unit is ready, Run complete-cluster-series-upgrade when the cluster has completed its upgrade.
03:17:17 swift-proxy/0*            active    idle   29       172.17.107.13   8080/tcp           Unit is ready
03:17:17 swift-storage-z1/0*       active    idle   30       172.17.107.41                      Unit is ready
03:17:17 swift-storage-z2/0*       active    idle   31       172.17.107.46                      Unit is ready
03:17:17 swift-storage-z3/0*       active    idle   32       172.17.107.29                      Unit is ready
03:17:17 tempest/0*                blocked   idle   33       172.17.107.35                      Ready for do-release-upgrade and reboot. Set complete when finished.
03:17:17 
03:17:17 Machine  State    DNS            Inst id                               Series  AZ    Message
03:17:17 0        started  172.17.107.5   fa80e484-90a6-4e91-a32d-68bcc1eac787  bionic  nova  ACTIVE
03:17:17 1        started  172.17.107.27  3c028c74-77c0-4f20-b97b-db3e03959f43  bionic  nova  ACTIVE
03:17:17 2        started  172.17.107.6   48d937ba-3721-453e-ae3f-e48ef9a8942b  bionic  nova  ACTIVE
03:17:17 3        started  172.17.107.20  8e32b176-d29e-406d-8580-b2e8772cf2a9  bionic  nova  ACTIVE
03:17:17 4        started  172.17.107.14  b8d4da7a-6177-4148-831b-173c96b07f25  bionic  nova  ACTIVE
03:17:17 5        started  172.17.107.31  e267f0b4-2e46-4e1f-964e-7b4dd3e27771  bionic  nova  ACTIVE
03:17:17 6        started  172.17.107.30  da52eaf0-3a30-46bc-a199-979d0bfb8e44  bionic  nova  ACTIVE
03:17:17 7        started  172.17.107.32  983de59c-9552-423b-b312-4bb2fcfd5f07  bionic  nova  ACTIVE
03:17:17 8        started  172.17.107.10  197d18f1-e9e7-44e1-b788-935cd255e26c  bionic  nova  ACTIVE
03:17:17 9        started  172.17.107.18  1b4d983c-5a77-4e89-b0d2-0b1fd32fc1fd  bionic  nova  ACTIVE
03:17:17 10       started  172.17.107.3   8fafb63f-5bbd-42b9-8c13-20dcd3a4d5df  bionic  nova  ACTIVE
03:17:17 11       started  172.17.107.11  cd414968-0c85-4a19-9329-13612a831c6d  bionic  nova  ACTIVE
03:17:17 12       started  172.17.107.37  38b1f9ad-a797-4bc6-878d-bb4755ac1398  bionic  nova  ACTIVE
03:17:17 13       started  172.17.107.9   35eed2bd-a95e-4b84-89d0-0bba924fbbb3  bionic  nova  ACTIVE
03:17:17 14       started  172.17.107.12  9c3be1dc-ab17-4647-b017-6b70e05f070f  bionic  nova  ACTIVE
03:17:17 15       started  172.17.107.7   ff248c14-ebee-4eec-a9cd-0150d2fff244  bionic  nova  ACTIVE
03:17:17 16       started  172.17.107.4   a760033b-c568-497a-947f-c3dc6b61eeac  bionic  nova  ACTIVE
03:17:17 17       started  172.17.107.8   1d8c1ad4-dcbb-48b3-94e3-b784115483e1  bionic  nova  ACTIVE
03:17:17 18       started  172.17.107.22  dd36f3dc-4817-4fed-8253-4c43e75472d4  bionic  nova  ACTIVE
03:17:17 19       started  172.17.107.34  cace71a7-f9c7-4f72-8d2e-fcadfd7c522a  bionic  nova  ACTIVE
03:17:17 20       started  172.17.107.47  2e9c7a5c-4440-4ab9-ae30-96d68c05fb35  bionic  nova  ACTIVE
03:17:17 21       started  172.17.107.24  f51fcee3-d2cc-4103-97f0-b9a8ed3d3d33  bionic  nova  ACTIVE
03:17:17 22       started  172.17.107.25  ec446168-8e95-40c3-9bb9-1cb29901ec14  bionic  nova  ACTIVE
03:17:17 23       started  172.17.107.43  93acf896-444c-4cdd-a6ac-6b6075b7b631  bionic  nova  ACTIVE
03:17:17 24       started  172.17.107.42  cf349c1f-f633-48b0-8bcc-edf4af291a68  bionic  nova  ACTIVE
03:17:17 25       started  172.17.107.28  6038a099-9f31-4d0d-afe4-78a426434117  bionic  nova  ACTIVE
03:17:17 26       started  172.17.107.16  cdf9fafe-0960-4afb-9dd0-f8596c2912bf  bionic  nova  ACTIVE
03:17:17 27       started  172.17.107.50  c65b9d71-016c-4d37-89c9-2022da193882  bionic  nova  ACTIVE
03:17:17 28       started  172.17.107.15  64f6cb89-1998-46d2-a990-5c27a8437eab  bionic  nova  ACTIVE
03:17:17 29       started  172.17.107.13  22bad8c5-5c1b-49d4-acc0-44343d3d4de2  bionic  nova  ACTIVE
03:17:17 30       started  172.17.107.41  7ac2157b-8cbe-410e-97fd-240956da3a0b  bionic  nova  ACTIVE
03:17:17 31       started  172.17.107.46  714b89de-3d04-47bb-9649-a12beb200006  bionic  nova  ACTIVE
03:17:17 32       started  172.17.107.29  729c50d0-a54e-4867-93f8-ee850bd62898  bionic  nova  ACTIVE
03:17:17 33       started  172.17.107.35  92951744-97fd-4050-be1b-c724eb7b3065  xenial  nova  ACTIVE
03:17:17 
03:17:17 ====>  f_lolo_log_puller  <=======================
03:17:17   File: '/var/lib/jenkins/tools/0/bot-control/tox.ini'
03:17:17   Size: 537       	Blocks: 8          IO Block: 4096   regular file
03:17:17 Device: fd01h/64769d	Inode: 3342521     Links: 1
03:17:17 Access: (0644/-rw-r--r--)  Uid: (  112/ jenkins)   Gid: (  116/ jenkins)
03:17:17 Access: 2019-10-12 18:40:46.759392677 +0000
03:17:17 Modify: 2019-10-12 18:40:46.759392677 +0000
03:17:17 Change: 2019-10-12 18:40:46.759392677 +0000
03:17:17  Birth: -
03:17:17 stat: cannot stat '/var/lib/jenkins/tools/0/bot-control/.tox/port-cleanup': No such file or directory
03:17:18 port-cleanup create: /var/lib/jenkins/tools/0/bot-control/tools/.tox/port-cleanup
03:17:23 port-cleanup installdeps: -r/var/lib/jenkins/tools/0/bot-control/tools/port-cleanup-requirements.txt
```

**Comment by AurelienLourot** [comment]
This charm has been [deprecated](https://docs.openstack.org/charm-guide/latest/2110.html) and removed from [these test bundles](https://github.com/openstack-charmers/charmed-openstack-tester/tree/master/tests/series-upgrade/tests/bundles).
